In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1. NumPy Array

In [3]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

In [ ]:
a[0]

In [ ]:
a[2:5]

In [ ]:
a[:6]

In [ ]:

a[3:]

In [ ]:
a[-1]

In [ ]:
a[-5:]

In [ ]:
a[-5:-1]

In [ ]:
np.size(a)

In [ ]:
np.shape(a)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:

a[0,0]

In [ ]:
a[1,:]

In [ ]:
a[:,-1]

In [ ]:
a[:,-1] = 0
a

### เซต colum-1=0

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

In [ ]:
np.size(a,1)

In [ ]:

np.ndim(a)

### Data is Matrix.
So, Matrix management == Data Management
rows = samples
columns = attributes, features

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

In [ ]:
np.array(np_mix_matrix[:,1], dtype = int)

## 3. Random


In [ ]:
import numpy as np
np.random.rand()

In [ ]:
np.random.randint(5)

In [ ]:
np.random.seed(100)
np.random.rand()

In [ ]:
np.random.rand(5,5)

In [ ]:

np.round(np.random.rand(5,5))

In [ ]:

a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

In [ ]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

### สุ่มมาขนาด5*5
### มี5 เลือก3
### ให้ choose=อันที่สุ่มมา

In [ ]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

In [ ]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

In [ ]:
i,j = np.where(np_matrix == 2)

In [ ]:
i

In [ ]:
j

In [ ]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

In [ ]:

np_matrix = np.random.randint(10,size = (5,5))
np_matrix

In [ ]:
result = (np_matrix == 2)
result

In [ ]:
np_matrix[result] = 99
np_matrix

In [ ]:
data = np.random.randint(5,size=(5,5)) + 1
data

## 4. Important Function

In [ ]:
np.max(data)

In [ ]:
np.max(data,0)

In [ ]:
np.max(data,1)

In [ ]:
np.sum(data)

In [ ]:
np.average(data)

In [ ]:
data[0,:]

In [ ]:

np.argmax(data[0,:])

In [ ]:
np.argmin(data[0,:])

In [ ]:
np.sort(data[0,:])

In [ ]:
np.argsort(data[0,:])

In [ ]:
np.arange(1,10,2)

In [ ]:
np.linspace(5,10,10)

In [ ]:

data = np.round(np.random.random((5,5))*3)
data

In [ ]:

data.shape

In [ ]:
data.reshape(1,25)

In [ ]:
tile = [[1,2],
        [3,4]]
tile

In [ ]:
np.tile(tile,(4,1))

## Assignment

## 2.

In [20]:
np_matrix = np.random.rand(10,5)
idx_choose = np.round(np_matrix[:,4])
np_matrix[:,4]=idx_choose 
np_matrix

array([[0.18615564, 0.35997065, 0.72161568, 0.99545225, 0.        ],
       [0.56238492, 0.45508018, 0.86058127, 0.21310541, 0.        ],
       [0.78466901, 0.18782771, 0.49712941, 0.48073622, 0.        ],
       [0.95317766, 0.59523613, 0.42620859, 0.7236477 , 0.        ],
       [0.47631398, 0.47990914, 0.19756306, 0.15065808, 0.        ],
       [0.04474551, 0.20759782, 0.4854075 , 0.26742677, 1.        ],
       [0.5747577 , 0.66935025, 0.11318528, 0.10096771, 1.        ],
       [0.99289243, 0.06782369, 0.88927161, 0.85937111, 0.        ],
       [0.28449925, 0.01220933, 0.60639996, 0.53174108, 1.        ],
       [0.24735643, 0.47273086, 0.84264285, 0.7522111 , 0.        ]])


## 3.


In [27]:

#idx = [1,2,3,4,5]
#np_matrix[idx,:]
#because index in this matrix have just 0-4 doesn't have 5.
idx = [0,1,2,3,4]
np_matrix[idx,:]
np_matrix = np.random.randint(3,size = (5,5))
i,j = np.where(np_matrix == 2)
j

array([3, 0, 1, 0, 1, 2, 4, 3])

## 4.


In [28]:
np_matrix = np.random.randint(10,size=(10,5))
lable_vector = np.random.randint(2,size=10)
np_matrix

array([[0, 5, 7, 9, 2],
       [4, 3, 1, 9, 4],
       [3, 5, 8, 4, 8],
       [7, 7, 6, 2, 5],
       [5, 0, 9, 0, 5],
       [6, 6, 5, 8, 5],
       [1, 8, 9, 3, 3],
       [0, 4, 5, 7, 3],
       [3, 1, 5, 0, 1],
       [3, 9, 5, 3, 6]])

In [29]:
lable_vector

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [33]:
condition = (lable_vector == 0)
train_data = np_matrix[condition]
train_data

array([[0, 5, 7, 9, 2],
       [4, 3, 1, 9, 4],
       [7, 7, 6, 2, 5],
       [1, 8, 9, 3, 3],
       [0, 4, 5, 7, 3],
       [3, 1, 5, 0, 1]])

In [34]:
condition = (lable_vector == 1)
test_data = np_matrix[condition]
test_data

array([[3, 5, 8, 4, 8],
       [5, 0, 9, 0, 5],
       [6, 6, 5, 8, 5],
       [3, 9, 5, 3, 6]])

## 5.

In [36]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[1, 3, 3, 2, 1],
       [2, 2, 1, 5, 3],
       [2, 4, 2, 4, 2],
       [1, 3, 5, 1, 1],
       [3, 1, 3, 3, 2]])

In [45]:
(-np.sort(data[0,:]*-1))

array([3, 3, 2, 1, 1])

## 6.


In [46]:
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
np_test[(np_test%3==0)]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

## 7.

In [49]:
np_test[(np.eye(5) == 1)] = 0
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16, 17,  0, 19],
       [20, 21, 22, 23,  0]])